# Database Configuration (Uses variables provided by the host)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/balik_gamit}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:09062063128}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# File Uploads (Limit size so your server doesn't crash)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
RESEND_API_KEY=re_Af15pMub_3qz4LtZQ321DyGUR8eN7Cxfo

# --- EMAIL CONFIGURATION ---
# Set to 'false' to allow registration without email verification
app.feature.email-verification=false
resend.api.key=${RESEND_API_KEY:re_Af15pMub_3qz4LtZQ321DyGUR8eN7Cxfo}

# --- CLOUDINARY CONFIGURATION ---
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:dq42jpo9m}
cloudinary.api_key=${CLOUDINARY_API_KEY:563361328648873}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:ay8mLlpZeG2S5NI0-51h5p_5AtU}
